// GET ALL POKEMON
export const SUCCESS_GET_ALL_POKEMON = "SUCCESS_GET_ALL_POKEMON";
export const LOADING_GET_ALL_POKEMON = "LOADING_GET_ALL_POKEMON";
export const FAILED_GET_ALL_POKEMON = "FAILED_GET_ALL_POKEMON";

// GET LANGUAGES
export const SUCCESS_GET_LANGUAGES = "SUCCESS_GET_LANGUAGES";
export const LOADING_GET_LANGUAGES = "LOADING_GET_LANGUAGES";
export const FAILED_GET_LANGUAGES = "FAILED_GET_LANGUAGES";
