import { ProductImages } from "./assets";

export const DATA_STORE = [
  {
    id: 1,
    productName: "Pokemon 3DS",
    img: ProductImages.PokemonProductOne,
    price: 120000,
    category: "Games",
    sales: true,
    discount: "50%",
  },
  {
    id: 2,
    productName: "Pokemon Battle Revolution",
    img: ProductImages.PokemonProductTwo,
    price: 100000,
    category: "Games",
    sales: false,
    discount: "",
  },
  {
    id: 3,
    productName: "Pokemon Blue Version",
    img: ProductImages.PokemonProductThree,
    price: 90000,
    category: "Games",
    sales: false,
    discount: "",
  },
  {
    id: 4,
    productName: "Pokemon Channel",
    img: ProductImages.PokemonProductFour,
    price: 150000,
    category: "Games",
    sales: false,
    discount: "",
  },
  {
    id: 5,
    productName: "Pokemon Mystery Dungeon Rescue Team",
    img: ProductImages.PokemonProductFive,
    price: 300000,
    category: "Games",
    sales: true,
    discount: "10%",
  },
  {
    id: 6,
    productName: "Pokemon Shield",
    img: ProductImages.PokemonProductSix,
    price: 400000,
    category: "Games",
    sales: true,
    discount: "30%",
  },
  {
    id: 7,
    productName: "Pokemon Shield",
    img: ProductImages.PokemonProductSeven,
    price: 400000,
    category: "Games",
    sales: true,
    discount: "30%",
  },
  {
    id: 8,
    productName: "Pokemon Wonder Beyonds",
    img: ProductImages.PokemonProductSeven,
    price: 200000,
    category: "Games",
    sales: false,
    discount: "0",
  },
  {
    // id: 2,
    productName: "",
    img: "",
    price: 0,
    category: "Action Figure",
    sales: false,
    discount: 0,
  },
  {
    // id: 3,
    productName: "",
    img: "",
    price: 0,
    category: "Exclusive",
    sales: true,
    discount: "30%",
  },
];
